Repository containers/image, pull requests merged in 2023-02, with the labels that each got.

#1816 Reconnecting blob reader
  docker/body_reader.go
  docker/body_reader_test.go
  docker/docker_client.go
Labels: enhancement

#1832 [release-5.24] Reconnecting blob reader
  docker/body_reader.go
  docker/body_reader_test.go
  docker/docker_client.go
  version/version.go
Labels: kind/feature

#1854 Make it clear that cleartext signatures are not accepted in simple signing
  docs/containers-signature.5.md
Labels: kind/bug

#1860 Fix builds of the ostree transport
  ostree/ostree_dest.go
Labels: kind/bug

#1789 manifest,zstd: give priority to `zstd` compressed images when pulling image from a manifest list
  copy/copy.go
  internal/manifest/docker_schema2_list.go
  internal/manifest/list.go
  internal/manifest/list_test.go
  internal/manifest/oci_index.go
  internal/manifest/oci_index_test.go
  internal/manifest/testdata/oci1.index.zstd-selection.json
  internal/manifest/testdata/oci1.index.zstd-selection2.json
  internal/manifest/testdata/oci1index.json
  internal/manifest/testdata/ocilist-variants.json
  internal/manifest/testdata/schema2list-variants.json
  internal/manifest/testdata/schema2list.json
  manifest/list_test.go
Labels: kind/feature

#1867 client: enable HTTP(S) keep-alive
  docker/daemon/client_test.go
  docker/daemon/daemon_dest.go
  docker/daemon/daemon_src.go
  docker/docker_client.go
  docker/docker_image.go
  docker/docker_image_dest.go
  docker/docker_image_src.go
  oci/layout/oci_src.go
  pkg/tlsclientconfig/tlsclientconfig.go
Labels: kind/feature
