Repository containers/image, pull requests merged in 2024-05, with the labels that each got.

#2412 Fix font choices in containers-transports.5
  docs/containers-transports.5.md
Labels: kind/bug

#2391 docker: support for requesting chunks without end offset
  copy/progress_bars.go
  docker/docker_image_src.go
  internal/imagesource/stubs/get_blob_at.go
  internal/private/private.go
  oci/archive/oci_src.go
  pkg/blobcache/src.go
Labels: kind/feature

#2394 Fixes to storage’s `GetBlob`
  storage/storage_src.go
Labels: kind/bug, jira

#2390 storage: cleanup staged layer if unused
  storage/storage_dest.go
Labels: kind/bug
